@extends('layouts.frontend')
@section('content')
    <!-- Page Header -->
    <section class="hero-gradient pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div class="max-w-7xl mx-auto text-center">
            <div class="space-y-6" data-aos="fade-up">
                <h1 class="text-4xl lg:text-6xl font-bold text-white leading-tight">
                    Islamic Books
                    <span class="block text-yellow-300">Collection</span>
                </h1>
                <p class="text-xl text-green-100 max-w-3xl mx-auto leading-relaxed">
                    Explore our comprehensive collection of authentic Islamic texts, from classical works to
                    contemporary scholarship
                </p>

                <!-- Search Bar -->
                <div class="max-w-2xl mx-auto mt-8">
                    <div class="search-container">
                        <svg class="absolute left-4 top-1/2 transform -translate-y-1/2 w-6 h-6 text-gray-400" fill="none"
                            stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                        <input id="mainSearchInput" type="text"
                            class="search-bar w-full pl-14 pr-6 py-4 bg-white rounded-2xl border-0 focus:outline-none text-lg shadow-2xl"
                            placeholder="Search books, authors, or topics...">
                        <button id="mainSearchBtn"
                            class="absolute right-2 top-1/2 transform -translate-y-1/2 bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-xl font-medium transition-colors">
                            Search
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Filters and Controls -->
    <section class="bg-white shadow-sm sticky top-16 z-40">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            <div class="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-6">
                <!-- Category Filters -->
                <div class="flex flex-wrap gap-3">
                    <button class="filter-btn active px-4 py-2 rounded-full font-medium" data-category="all">
                        All Books
                    </button>
                    <button class="filter-btn px-4 py-2 rounded-full font-medium" data-category="quran">
                        Quran & Tafsir
                    </button>
                    <button class="filter-btn px-4 py-2 rounded-full font-medium" data-category="hadith">
                        Hadith
                    </button>
                    <button class="filter-btn px-4 py-2 rounded-full font-medium" data-category="fiqh">
                        Fiqh
                    </button>
                    <button class="filter-btn px-4 py-2 rounded-full font-medium" data-category="history">
                        History
                    </button>
                    <button class="filter-btn px-4 py-2 rounded-full font-medium" data-category="theology">
                        Theology
                    </button>
                </div>

                <!-- Sort and View Controls -->
                <div class="flex items-center gap-4">
                    <div class="flex items-center space-x-2">
                        <label class="text-sm font-medium text-gray-700">Sort by:</label>
                        <select id="sortSelect"
                            class="sort-dropdown border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500">
                            <option value="title">Title A-Z</option>
                            <option value="author">Author</option>
                            <option value="downloads">Most Downloaded</option>
                            <option value="rating">Highest Rated</option>
                            <option value="recent">Recently Added</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Books Grid -->
    <section class="py-12 bg-gray-50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div id="booksGrid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                <!-- Book Card Template - Multiple cards will be generated by JavaScript -->
            </div>

            <!-- Load More Button -->
            <div class="text-center mt-12">
                <button id="loadMoreBtn"
                    class="bg-green-600 hover:bg-green-700 text-white px-8 py-4 rounded-xl font-semibold text-lg transition-all duration-300 transform hover:scale-105 shadow-lg">
                    Load More Books
                </button>
            </div>

            <!-- Pagination -->
            <div class="flex justify-center items-center space-x-2 mt-12" id="pagination">
                <button class="pagination-btn px-3 py-2 rounded-lg">Previous</button>
                <button class="pagination-btn active px-3 py-2 rounded-lg">1</button>
                <button class="pagination-btn px-3 py-2 rounded-lg">2</button>
                <button class="pagination-btn px-3 py-2 rounded-lg">3</button>
                <span class="px-3 py-2 text-gray-500">...</span>
                <button class="pagination-btn px-3 py-2 rounded-lg">12</button>
                <button class="pagination-btn px-3 py-2 rounded-lg">Next</button>
            </div>
        </div>
    </section>
@endsection



